### ISSUE TITLE
network logging

### ISSUE THREAD

**Issue by benjyz** [SaitoTech/saito-lite#1]
add more info about network in logs

**Comment by arpee** [comment]
We are currently swimming in debug logs that just hang around - it's true.

What did you have in mind here? (might form part of a broader conversation.

**Comment by trevelyan** [comment]
two key classes:

 - network (addPeer && addRemotePeer in particular)
 - peer (which handles socket management and incoming messages)

The network class contains all of its peers in an array. Shouldn't be too
hard to add logging information.

Opportunity to define how information is desired / needed.
