### ISSUE TITLE
Game-breaking instances

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#104]
Will use this issue to upload every game-breaking instance that we've found so far.

**Comment by Tuch-o** [comment]
Offensive Missiles allows the player to pull a card from the opponents hand and the play it or discard it. Neither option work. Nothing happens when you click it.

Console shows this:
![image](https://user-images.githubusercontent.com/54612963/79477408-2b0a9a00-7fd8-11ea-9126-5f580a0c94bd.png)

**Comment by Tuch-o** [comment]
Wave and Smile event allows the US to escalate or deflate DEFCON level but you get stuck at this screen and the game can't be advanced:

![image](https://user-images.githubusercontent.com/54612963/79519901-3afb9b80-8023-11ea-83d5-65c7333c4360.png)

Clicking the 'done' button does nothing and you can click to escalate or deflate indefinitely, even making the DEFCON marker disappear if you go under/over the normal levels:

![image](https://user-images.githubusercontent.com/54612963/79520067-b2312f80-8023-11ea-8a23-87e0f6674816.png)

**Comment by arpee** [comment]
I has a similar issue :

 ```
if (this_card.side == "neutral" || this_card.side == me) {
```
is barfing as card is not defined in:
```
function playerPlayStrategyCard(card) {
```

But I did not note the card.

**Comment by trevelyan** [comment]
will have to see about Wave and Smile

the earlier issue is fixed.

If the W&S was triggered by "share_card" it will be fixed too. unsure.
