### ISSUE TITLE
USSR gets Bear Has Landed bonus even if it hasn't reeached it yet

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#105]
USSR gets to discard a card at the end of the turn even it it didn't reach Bear Has Landed.

You can see it here without any country spacing a card
![image](https://user-images.githubusercontent.com/54612963/79482778-4b8a2280-7fdf-11ea-8c54-a84f340cdb8b.png)

This time with boh countries at Earth Satellite
![image](https://user-images.githubusercontent.com/54612963/79483137-d9660d80-7fdf-11ea-9e2f-54e415819fe8.png)

**Comment by Rammko** [comment]
Fixed by David
