### ISSUE TITLE
Truman doesn't show the list of countries to remove influence from

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#117]
![image](https://user-images.githubusercontent.com/54612963/81359356-f05fc300-90a6-11ea-84b7-f92238d3a858.png)

Triggering Truman should show all the possible targets to remove influence from, Romania and Finland in this case.  US can't select the target and the game can't be further advanced.

**Comment by trevelyan** [comment]
Click on the country

**Comment by trevelyan** [comment]
We can print a list and make it selectable too

**Comment by Tuch-o** [comment]
Lol, my bad there. I uploaded the wrong thing
