### ISSUE TITLE
Has this been tested for Windows?

### ISSUE THREAD

**Issue by davesgonechina** [SaitoTech/saito-lite#153]
Not a Windows user so quite possible I'm doing something wrong, but happened to try installing on a Windows machine from Powershell and ran into a number of errors that I suspect are because `npm` relies on the command shell and Windows conventions differ from Linux when it comes to forward vs. backslash in paths, `NODE_ENV` vs `SET NODE_ENV`, `%` vs. `$` for bash variables, etc.

As a result, after running `npm install`, I see `Exit Status 1` errors for `npm run nuke` (`./compile` vs `.\compile` I believe is the problem) and `npm start` (`NODE_ENV` vs `SET NODE_ENV`).

Has anyone successfully run `saito-lite` on Windows 10? In the meantime I'll simply switch to a Linux environment.

**Comment by trevelyan** [comment]
Thanks Dave

Will look

**Comment by Melisa-Surja** [comment]
I installed it on windows... but with ubuntu. So all server + git commands are run on ubuntu.

You can install ubuntu for windows from Windows Store.
