### ISSUE TITLE
Duplicated content in litepaper.pdf

### ISSUE THREAD

**Issue by HerrBertling** [SaitoTech/saito-lite#170]
Hi 👋 

I‘ve read your litepaper.pdf and noticed that on page 4, the list contains the same description for the first three items. I‘m pretty sure that this is not intended 😄 maybe you want to fix that 😊

Have a great day!
Markus

![5836E7EE-4C7B-454E-B98A-A1A8014D5EAF](https://user-images.githubusercontent.com/1827373/118098188-e405f880-b3d3-11eb-8df8-3b1577f9d391.jpeg)

**Comment by estapeluo** [comment]
Thanks for bringing this to use - we are aware of it!

**Comment by HerrBertling** [comment]
Wanted to check whether the new version was up, but now the whole document is missing 🙈 https://saito.io/saito-litepaper.pdf

**Comment by escapedcat** [comment]
Litepaper got removed from homepage (Link and PDF-file) because the project doesn't like this approach.  
There will be another way to help people understand the project in a more simple way in the future.
