### ISSUE TITLE
Red Scare Quagmire bug

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite#176]
http://puu.sh/HGEre/0adcebeec2.jpg

opponent was able to pick a 2 ops card for quagmire even under red scare, and then picked a 1ops card to end quagmire

**Comment by trevelyan** [comment]
I'm going to close this because I think it is fixed.

I remember fixing something like this -- it was an edge-case introduced by another bug-fix.

If it happens again let's re-open.
