### ISSUE TITLE
http://saito.io/chat/ takes you to a blank page

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#19]
Tucho's here, let's kill some bugs.

Clicking on http://saito.io/chat/ sends you to a blank page where you can't do anything

Screenshot attached:
![image](https://user-images.githubusercontent.com/54612963/70045101-e7b80d80-1599-11ea-9bdf-8fff95e4c111.png)

**Comment by arpee** [comment]
@BearGuy is on this - as we speak.

**Comment by arpee** [comment]
oops

**Comment by Tuch-o** [comment]
Same thing happens when clicking on Forum

![image](https://user-images.githubusercontent.com/54612963/70101735-41f1b680-160c-11ea-812f-aad3d2f258d7.png)

**Comment by BearGuy** [comment]
We haven't redone the forum, so going to saito.io/forum should just 404. 

Fixed blank chat page, should display the server chat room on load now
