### ISSUE TITLE
Add 'dot arcade' to home page.

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite#190]
Add a 'dot arcade' section and link to the home page.

* Add section at place 3 (between sectionWrapper2 and sectionWrapper3 (does not need to follow this naming convention).

* Add content from saito.io/dotacrade to this section.

* Change 'Play Poker' to 'Play Games'

* Make sure it's still nice and responsive

* Add anchor #dotarcade above section

* add top menu link to saito.io/#dotarcade between 'Get Saito Tokens' and '中文'

**Comment by arpee** [comment]
For now we want this to be 'Dot Arcade' promoting the colaboration - rather than just 'arcade'. So can the header linke be updated and the same image used (for now) as the /dotarcade page.

I am also seeing issues when the page/view aspect is very tall...

Seems like:  ```min-height: 80vh;``` in the definition at line 388 is unnecessary - thought I don't know what negatives side effects 
occur if it's removed. Can you check?

Thanks.

**Comment by f8daniel** [comment]
OMG, I never saw this comment until today.
Fixed the issues raised here and in the (now updated) pull request, i.e. keeping the branding more consistent and not littering the css with unnecessary commands/commented out commands.

I wasn't able to replicate any issues with the responsive layout on monster screen sizes (stretched out to 1000s of pixels either way), so should be good to merge back into the master branch and prune this fcking timeline.

> 
> 
> For now we want this to be 'Dot Arcade' promoting the colaboration - rather than just 'arcade'. So can the header linke be updated and the same image used (for now) as the /dotarcade page.
> 
> I am also seeing issues when the page/view aspect is very tall...
> 
> Seems like: `min-height: 80vh;` in the definition at line 388 is unnecessary - thought I don't know what negatives side effects
> occur if it's removed. Can you check?
> 
> Thanks.

**Comment by arpee** [comment]
Commented in the Pull request - the idea is to have the Play button in the dotarcade section on the home page trigger the same functionality as clicking the play button at /dotarcade.

**Comment by arpee** [comment]
All good in my testing. Triggers the popup and hits the endpoints just fine.

Thanks.  Will pull.
