### ISSUE TITLE
Solitrio

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite#192]
1) Won't launch from arcade (b/c phantom variable "data")
2) Reshuffling doesn't work (b/c misused "this")
3) Reshuffling doesn't preserve chains
4) Should add 
- Automatic game over if no available moves
- Should add an undo button
- Add new game button
- Save state on exit
5) Polish instructions/user messaging

**Comment by arpee** [comment]
Think it would be good to add:

* indication of selected card (border/shadow/grey out)


Lets move on to this as the next task.

**Comment by arpee** [comment]
Also spotted save state - that could simply go into the options/config storage right now. 

Next step would be to add it to the archive system as emails are. I have a stub ticket for this in 'todo'.

**Comment by f8daniel** [comment]
The selected cards are already marked with a change in opacity that slightly greys them out.
I actually misunderstood the rules of the game because the instructions were so poor, so #3 isn't actually an issue. 
Some of the to-do's are a bit beyond my current understanding, but I am aiming to push a partial update before the weekend.

**Comment by trevelyan** [comment]
Having instructions would be good.

**Comment by f8daniel** [comment]
Yes, I already rewrote the instructions, part of task #5. It's awkward talking about this as I just broke something so am not at a point to make a commit or pull request, lol

**Comment by arpee** [comment]
This is nice - will pull this and add saving on exit and undo - not done - unsure if WIP for another card.
