### ISSUE TITLE
Wordblocks UI

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite#195]
### Short-term fixes (to be included in initial push):

1. Clean up CSS 
    1.1 Centering Stars/Bonus Tile 
    1.2 Better transparency to show which letter tiles were played on top of bonus spaces

2. Change Game Menu
    2.1 Add rules/play instructions
    2.2 Remove "Log" (because it doesn't do anything. Tries to change the class on a non-existent DOM element, causes error)
    2.3 Improve layout/formatting of Game Stats
    2.4 *maybe* make a distinction between log and stats, where we render the ordered list of words played in the game so far vs other gameplay statistics, such as avg play score, avg word length, number of bonus tiles, best play, etc.

3. Force uppercase in storage/display of played words (for consistency) if we are doing keyboard input, I don't want user to think about having to push shift/caps lock since game tiles are displayed in uppercase letters to begin with

4. Improve feedback to user about their score
    4.1 Include _all_ the words formed and their scores for each play (can divide between main, i.e. entered, word and additional words) 
    4.2 Show the math on scoring, including bells and whistles to emphasize bonuses

### Long-term fixes (no idea if even possible)

1. The click-n-dragable tiles in the tile rack aren't very responsive, e.g. impossible to move a tile into first position unless initially click mouse along its right edge

2. Typing to discard tiles is cumbersome, would be better to have a trash can icon, with click-and-drag to discard (plus a "Draw New Tiles" button to finish discarding process and end turn)

3. Click/Select Orientation/Type Word is difficult game play mechanic (requires a lot of manipulation in user's working memory). Would be nice to allow players to interactively move tiles between rack and board to see placement before submitting word.

**Comment by f8daniel** [comment]
UPDATE:
Found a bug, when resuming a game, it got stuck on one player, allowing multiple moves but not communicating with other player...
![image](https://user-images.githubusercontent.com/70703104/129759565-8b819516-a8ee-48ac-bb89-69b25cff5241.png)

**Comment by f8daniel** [comment]
There is an inconsistency between messaging and implementation of game rules.
It says you lose points for discarding (which would be an interesting twist on classic Scrabble rules), but the penalty is not implemented.
Should I:
a) change the message
b) implement a point deduction
![image](https://user-images.githubusercontent.com/70703104/130097778-5edbf02b-85c3-4f7c-ab75-5344744742c7.png)

**Comment by trevelyan** [comment]
Lets change the messaging. People are already penalized by inability to
place. Imo.

**Comment by arpee** [comment]
Agree
