### ISSUE TITLE
Solitrio Polish

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite#196]
Add undo button
Add save state to wallet

**Comment by f8daniel** [comment]
In all my testing, I never once managed to win the game, otherwise I would have found this bug.
Will be interesting to see if any users flag it before I get around to fixing.
![image](https://user-images.githubusercontent.com/70703104/130649649-3a8e9e97-4c42-4d34-8f65-55b63d677bae.png)

**Comment by trevelyan** [comment]
You have never won Solitrio?

Dan....
