### ISSUE TITLE
404 trying to start a TS match

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#20]
Well this one is critical lol.

Sent an invite and took it using Incognito to test the new arcade but this really subtle 404 greeted me:
![image](https://user-images.githubusercontent.com/54612963/70046703-f18f4000-159c-11ea-89d8-ce21ad82dbdf.png)

**Comment by trevelyan** [comment]
thx -- I will try to fix what is broken.

**Comment by BearGuy** [comment]
Fixed
