### ISSUE TITLE
polkadot/parity issue - What is going on here?

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite#220]
![saito-errors](https://user-images.githubusercontent.com/70703104/136867308-22a4a800-248b-455e-86a2-16cf9580c853.png)

I'm trying to debug my own code, and freaking out b/c of pages of errors in the console... 
Oh wait, this is part of the master branch, and is happening on the live site as well...
...so if I didn't cause this in my local repository, what is going on?

Obviously the site still works despite these verbose issues, but it's hard to be productive when I have to spend time sorting out my errors from cosmic background radiation.

**Comment by arpee** [comment]
I have had a quick look and googling is surprisingly unhelpful.

We did trial upgrading the scep256k1 lib - but downgraded as there is more work required to update the library so postponed and reverted. Version is the same as previously used.

Will dig deeper.

**Comment by trevelyan** [comment]
I may have caused issues.

Unintentional.

Let me do a merge of the latest game changes and get us to a known good
state.

Apologies.
