### ISSUE TITLE
Wordblocks Upgrade (Mouse Controls)

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite#252]
The click-n-dragable tiles in the tile rack aren't very responsive, e.g. impossible to move a tile into first position unless initially click mouse along its right edge

    Typing to discard tiles is cumbersome, would be better to have a trash can icon, with click-and-drag to discard (plus a "Draw New Tiles" button to finish discarding process and end turn)

    Click/Select Orientation/Type Word is difficult game play mechanic (requires a lot of manipulation in user's working memory). Would be nice to allow players to interactively move tiles between rack and board to see placement before submitting word.

**Comment by arpee** [comment]
Agree an added trash icon (maybe one that appears and lets the user just drop tiles on it, and disables when a tile is placed on the board?).
