### ISSUE TITLE
<div id="alert-shim"> freezes the game 

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#37]
Bugtesting game against myself. Couped Argentina as the US and the game got stuck at this screen:
![image](https://user-images.githubusercontent.com/54612963/72005723-a6fc8580-3224-11ea-80cf-1bfe9f3ec3ea.png)

The other player sees this tho. The OK button works fine and the game can be continued on his side so it must be an interface bug.
![image](https://user-images.githubusercontent.com/54612963/72005765-b976bf00-3224-11ea-947e-505a5322f798.png)

Took a look at the console and deleted this element: 
![image](https://user-images.githubusercontent.com/54612963/72006126-5e919780-3225-11ea-82ee-0810d945a9db.png)

Deleting it fixed the issue, game went back to normal and I kept on playing:
![image](https://user-images.githubusercontent.com/54612963/72006409-ed061900-3225-11ea-9351-52f3c6d035fc.png)

**Comment by Tuch-o** [comment]
Also happens when the game ends:
![image](https://user-images.githubusercontent.com/54612963/72112608-667c3500-3314-11ea-8df5-4a9bd755945b.png)

**Comment by Tuch-o** [comment]
NOTE: Happens after every coup, not specific to Argentina. Refreshing fixes it too.

**Comment by trevelyan** [comment]
i don't understand what this means.

How to replicate the problem?

**Comment by Tuch-o** [comment]
I made a gif to better illustrate my point:

![coup](https://user-images.githubusercontent.com/54612963/74987740-4448fd00-5412-11ea-9aeb-27895c0b5f36.gif)

After launching a coup, the screen with the results gets covered by a grey overlay that makes the OK button unclickable. There are two ways to fix it: Refreshing the page or opening the console and deleting the **div id="alert-shim"** element.

**Comment by trevelyan** [comment]
Ah... I get this.

I think this is something that Richard is probably better off at handling.

**Comment by Tuch-o** [comment]
Fixed, closing.
