### ISSUE TITLE
Can't send emails

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#40]
Tried to send myself an email. Everything seems to work fine in the email app, but when you hit 'send', nothing happens. Both the regular Send button and the Send Saito button have no effect whatsoever.

![image](https://user-images.githubusercontent.com/54612963/72156477-0923ca80-338c-11ea-9bc8-1285f6f65a7c.png)

**Comment by trevelyan** [comment]
This is probably a DNS issue.

**Comment by Tuch-o** [comment]
Actually, I tried to send it using my actual address (mKMuGynjYTytTex9xX1YGppjcKkuZ3iWqqNypUVJGzUe) instead of the nickname I registered and it worked. Is that intended behaviour? I suppose you should be able to email using nicknames too.
