### ISSUE TITLE
Repeated messages in chat

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#42]
Take a look at the following screenshots:

![image](https://user-images.githubusercontent.com/54612963/72758489-50d6fd00-3ba9-11ea-96ac-da62116a4c8f.png)

![image](https://user-images.githubusercontent.com/54612963/72761769-6d783280-3bb3-11ea-9032-61250e55cea6.png)

When someone sends a message, it shows up a bunch of times on my chat. I seem to be the only one affected and refreshing does fix it but it is a bug nonetheless. Using Chrome

**Comment by arpee** [comment]
Can't replicate now. Looks like this was fixed by a passing change.

Can you test out? Thanks.

**Comment by Tuch-o** [comment]
Seems to be fixed, haven't seen it in a while. I'll reopen this in case it happens again.

**Comment by Tuch-o** [comment]
Happened again, but there's a twist. 

I was trying to replicate a bug mentioned by Duke that only seems to happen on Firefox so I opened the arcade on Firefox and sent a test message:

Firefox, look at the chat:
![image](https://user-images.githubusercontent.com/54612963/73028532-1a4cec80-3e0c-11ea-9705-e664ed3285e7.png)

Chrome - Incognito:
![image](https://user-images.githubusercontent.com/54612963/73028548-25078180-3e0c-11ea-8da7-3a1469454c4d.png)

Chrome - Regular:
![image](https://user-images.githubusercontent.com/54612963/73028614-47010400-3e0c-11ea-95ef-3754e790c0dc.png)

So it doesn't happen on Firefox nor Incognito Chrome. Only happens using normal Chrome which is weird since everything else appears to be working just fine.

**Comment by estapeluo** [comment]
Chat got a revamp and no more duplicates chats.
