### ISSUE TITLE
Showing the name of invite's creators

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#44]
Avatars work too, but having both avatars and names would improve it.

Tucho's fantastic and super complex suggestion:

Turning this
![image](https://user-images.githubusercontent.com/54612963/72903633-f2726180-3d03-11ea-86af-f5a029fe6825.png)

Into this
![image](https://user-images.githubusercontent.com/54612963/72903712-2057a600-3d04-11ea-84f5-cd76673bbdd2.png)

**Comment by arpee** [comment]
I have added this as a mouse-over. This seems the best way to handle this given the space.

**Comment by Tuch-o** [comment]
Working indeed. Really like the mouse-over solution. Closing.
