### ISSUE TITLE
Socialist Governments only shows 2 inf removed

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#45]
The card works as intended, you can take out 3 influence but the log only shows 2.

Screenshots attached:

Pre-Soc Gov. Look at Italy and WG:
![image](https://user-images.githubusercontent.com/54612963/72984121-4e4af200-3db9-11ea-982e-6c77f4cd48b3.png)

Post-Soc Gov. Look at the log:
![image](https://user-images.githubusercontent.com/54612963/72984351-e052fa80-3db9-11ea-9289-869f1ddf2323.png)

**Comment by clayrab** [comment]
Is this still an issue?
