### ISSUE TITLE
Can't cancel a game

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#46]
Tried to cancel a game against Telechris but couldn't. Same happens to him.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/54612963/73030159-6f3e3200-3e0f-11ea-949e-1e82b3d83889.gif)

This is what the console looks like rn:
![image](https://user-images.githubusercontent.com/54612963/73030262-a3b1ee00-3e0f-11ea-92b7-5e301db36bca.png)

Also uploaded the whole console so you can take a look at it if you want to:
[WbConsole.txt](https://github.com/SaitoTech/saito-lite/files/4105930/WbConsole.txt)

**Comment by estapeluo** [comment]
Same problem, but mostly on game that doesn't start. For this i did a 6-player chess (Yes, 6-player itself an issue, minor) same behavior of the button.
![image](https://user-images.githubusercontent.com/59634305/73048446-93b9fe80-3e4f-11ea-84c8-28b77bb550ff.png)
