### ISSUE TITLE
Can't start games

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#48]
Arcade has been completely dead today. Games can't be started. Invites are dead upon accepting, they all just freeze like this.
![image](https://user-images.githubusercontent.com/54612963/73101846-fb5f6080-3ec6-11ea-8035-20d5c2a1cf44.png)

Also, games remain on the arcade even if someone takes them so the arcade gets cluttered up with dead invites. Resetting wallets also doesn't fix the issues.

**Comment by estapeluo** [comment]
I manage to start 5 out of 6 game son 2 fresh wallets (from incognitos).
2xChess, 2xTwilight, 1 Wordblock. Last wordblock didnt init and showed the 2 icons - cancel button.

**Comment by Tuch-o** [comment]
Still can't start games, just tried accepting one on Incognito but I couldn't and now the Join button is gone. 

Fresh wallets don't work for me, I get the same result.

![image](https://user-images.githubusercontent.com/54612963/73214022-b71ecb00-4127-11ea-92cb-7b03f46d333b.png)

**Comment by Tuch-o** [comment]
Happening again, hitting the Join button has no effect.
