### ISSUE TITLE
Vietnam Revolts affects US when playing the China card

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#60]
Simple yet very important bug. US gets the bonus from Vietnam Revolts when playing China.

Take a look:

USSR headlines Vietnam Revolts and then USA plays the China card for 6 ops in Thailand, getting both China's and VR's bonuses.
![image](https://user-images.githubusercontent.com/54612963/74781538-04e6a900-5278-11ea-997e-b48d7f2b061d.png)

![image](https://user-images.githubusercontent.com/54612963/74781578-162fb580-5278-11ea-814d-080203a2813c.png)

This only affects China and doesn't apply to the rest of the cards:
Played all of East European Unrest's ops into SE Asia and didn't get the bonus
![image](https://user-images.githubusercontent.com/54612963/74782040-1c726180-5279-11ea-8c1e-31b37ae4c171.png)

**Comment by trevelyan** [comment]
fixed

**Comment by Tuch-o** [comment]
Closing.
