### ISSUE TITLE
Playing Decolonization allows the USSR to place inf without adjacency

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#63]
![image](https://user-images.githubusercontent.com/54612963/74995806-4a49d880-5428-11ea-9780-9d67638a9f50.png)

Take a look at the log. First, USSR triggers Decolonization and places 1 each in Somalia, Nigeria, Burma and Indonesia. On USSR's following AR, They get to place inf in any African or SE Asian country even if there's no adjacency. 

In this case I played Warsaw Pact for 3 ops and placed 1 each in Thailand, Zaire and SE African States.

**Comment by trevelyan** [comment]
this is a nice bug.

i'll try to get it fixed soon.

**Comment by Tuch-o** [comment]
Seems to be fixed, will close but i'll keep an eye on it.
