### ISSUE TITLE
Brush War doesn't account for modifiers

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#67]
Two instances of Brush War succeeding on impossible odds. -5 modifier on the first case and -4 on the second. It isn't possible to roll 3-6

![image](https://user-images.githubusercontent.com/54612963/75298141-0ed45300-5808-11ea-82b8-b7a0c31866af.png)

![bw](https://user-images.githubusercontent.com/54612963/75298485-00d30200-5809-11ea-9f85-4f477ed750aa.png)

**Comment by Rammko** [comment]
Wasnt able to figure this one out, printing the modifier on the log confirmed that no matter where the target was, modifier was always 0. @trevelyan sorry, cant seem to find a fix for it and would rather not break such a crucial card so im passing the baton back to you

**Comment by trevelyan** [comment]
ok

**Comment by trevelyan** [comment]
fixed in latest push.
