### ISSUE TITLE
Chess doesn't show the player's names

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#70]
Title. You can't see the name (or the address) of your opponent when inside a Chess match

![image](https://user-images.githubusercontent.com/54612963/75682361-b23fc080-5c6b-11ea-9174-fff18e1d19f4.png)

**Comment by Darkuso** [comment]
This can is fixed if u click in the "Chess" word next to Saito. It refresh the board and shows the opponent name or hash. I'll look into this one.

**Comment by estapeluo** [comment]
Done - will show hash if it doesn't have an identifier
