### ISSUE TITLE
Korean War roll doesn't account for US control of North Korea

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#71]
Credit to the great JAN for this find. Korean War's code only counts the modifiers from Japan and Taiwan, thus making it possible for NK to win the war even if USA controls the 3 adjacent countries.

**Comment by trevelyan** [comment]
Was this real?

Does it need fixing?

**Comment by Tuch-o** [comment]
Was real, Arks fixed it.
