### ISSUE TITLE
Hovering the mouse over invites shows the sender's address instead of the name

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#75]
As in showing this:
![image](https://user-images.githubusercontent.com/54612963/76006212-8aa65d80-5ee2-11ea-9b63-5e5f51348325.png)

Instead of this:
![image](https://user-images.githubusercontent.com/54612963/76006289-a0b41e00-5ee2-11ea-89ff-ba846c786604.png)

This doesn't happen every single time and sometimes works correctly. Not sure what causes it to switch but it makes it really tough to know who sent the invites.

**Comment by estapeluo** [comment]
This is related to how wallet identifiers propagate and get stored - if you don't see the identifier, you need to wait for that person to propagate it (for example a simple chat message).
