### ISSUE TITLE
Clicking on Cards/Display/Players and then clicking on status Locks the UI when selecting what to do with a card or an event in the console

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite#79]
As the title says this bug locks the UI until the user refreshes 

![UI Lock](https://user-images.githubusercontent.com/61713323/76246397-fdca0f80-6213-11ea-875c-30f68df72433.gif)

It doesn't happen when selecting a card, only when choosing what to do with said card or situations where the player is forced to click somewhere in the console to select an option (bear/eagle has landed for example)

**Comment by trevelyan** [comment]
users can reload for now.

>
