### ISSUE TITLE
Discard Pile showing Removed cards - Salt Negotiations possible critical issue

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite#86]
As the title states, there are cards removed from game in the discard pile. While this is a visual issue, it creates problems when using Salt Negotiations as its pulling removed cards from the discard pile as possible targets to retrieve, clicking on these cards does not actually pull them however and the UI for Salt remains active prompting you to pick cards until you pick a non removed card at which point, any removed cards you clicked on will show up on as unusable cards in your hand however many times you clicked (example: clicking on Quagmire after its already been removed if its on the discard pile 9 times will give you 9 unusable copies of Quagmire). This is already an issue but it can cause games to get stuck if any card that alters your hand comes into play afterwards, Missile Envy, Aldrich, 5YP, Grain Sales, Ask Not, and even if you are at Bear/Eagle has landed and you choose to discard a card are examples of this since the game is asking you to discard/share a card that has glitched values. A fix for Salt Negotiations could fix the issue with it but it would be better to nip the issue in the bud rather than applying a Band-Aid on it

**Comment by Tuch-o** [comment]
@trevelyan Can you check this out?

**Comment by trevelyan** [comment]
Yeah, I'll have to take a look.

I think that headline cards are not being removed if evented once we get up
past 5 in the space race, so it might be related to that.

**Comment by trevelyan** [comment]
I believe this is fixed.

What appeared to be happening is that events played during the headline phase were getting discarded and THEN removed. This put them in both the "discard" and "removed" pile, and Salt Events was then displaying them even if they could not be selected.

I can't guarantee that the fix doesn't break something, although if it does it will be a secondary issue that we need to fix.
