### ISSUE TITLE
Quag/Bear an opponent with only 1ops cards AND at least 1 scoring card in hand causes them to be able to play 1ops cards for Bear/Quag

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite#87]
When using bear/quag on someone who only has 1ops cards AND scoring cards, the game will ask them to use a scoring card, but they will see the 1ops cards along with the scoring cards and then they can use one of the 1 ops cards instead.
they cant have any 2ops or higher, and they NEED to have at least one scoring card for it to trigger.

**Comment by trevelyan** [comment]
nice find

**Comment by Tuch-o** [comment]
@trevelyan can you check this one too?

**Comment by trevelyan** [comment]
yeah, I'll fix this.

understand the problem right from the description.

thx guys

**Comment by trevelyan** [comment]
i believe this is fixed.
