### ISSUE TITLE
Iran-Iraq War doesn't show the roll

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#91]
![image](https://user-images.githubusercontent.com/54612963/77014942-c3feb480-6949-11ea-8d6c-8c9dc793d208.png)

When Iran-Iraq War is triggered, it gives you the mil ops but it doesn't show the dice roll. Not sure if the bug is only visual or if the dice roll isn't happening at all. 

Should be noted that I tested it 3 times and they all failed but that's a small sample size. Will keep testing.

**Comment by trevelyan** [comment]
fixed -- was only a problem for invasions of Iraq -- will update in next commit.
