### ISSUE TITLE
Stuck TS Game

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#99]
Just had a bugtesting TS match getting stuck - this is the state of the game

US:
![image](https://user-images.githubusercontent.com/54612963/78309485-0fec5480-7519-11ea-9b04-add73e3924c8.png)

US also didn't receive cards at the start of the turn:
![image](https://user-images.githubusercontent.com/54612963/78309510-1f6b9d80-7519-11ea-9289-18cf4e166ba6.png)

USSR:
![image](https://user-images.githubusercontent.com/54612963/78309518-285c6f00-7519-11ea-8481-87cbd319eee2.png)

US console:
[MRTsaito.io-1585870394484.log](https://github.com/SaitoTech/saito-lite/files/4424298/MRTsaito.io-1585870394484.log)

USSR console:
[OPERAsaito.io-1585870065285.log](https://github.com/SaitoTech/saito-lite/files/4424305/OPERAsaito.io-1585870065285.log)

**Comment by Tuch-o** [comment]
Another Instance:

US:
![image](https://user-images.githubusercontent.com/54612963/78375170-69489800-759a-11ea-8cfd-02cbc8c89954.png)

USSR:
![image](https://user-images.githubusercontent.com/54612963/78375212-78c7e100-759a-11ea-8089-c80b5af84aac.png)


Consoles:
US: [2MRT.log](https://github.com/SaitoTech/saito-lite/files/4428092/2MRT.log)

USSR: [2OPERA.log](https://github.com/SaitoTech/saito-lite/files/4428099/2OPERA.log)

Should be noted that connection was very unstable during this match, which caused the websocket errors.

**Comment by trevelyan** [comment]
We are preparing an update that will do better with pending txs and
hopefully solve these problems.

It will take another 36 hours, I believe.
